-- ==========================================
-- CamTrace v1.0 - Schema Definition (Oracle 19c)
-- ==========================================

-- ----------------------------------------------------------------------------
-- 1. Sequences
-- ----------------------------------------------------------------------------
CREATE SEQUENCE SEQ_TCL_CAM_ROLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TCL_CAM_USER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TCL_CAM_CHECKLIST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TCL_CAM_INSPECTION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TCL_CAM_RESPONSE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TCL_CAM_PHOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TCL_CAM_AUDIT START WITH 1 INCREMENT BY 1;

-- ----------------------------------------------------------------------------
-- 2. Tables
-- ----------------------------------------------------------------------------

-- ROLE
CREATE TABLE TCL_CAM_ROLE (
    ROLE_ID NUMBER NOT NULL,
    ROLE_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TCL_CAM_ROLE PRIMARY KEY (ROLE_ID)
);

COMMENT ON TABLE TCL_CAM_ROLE IS 'Roles available in the application';
COMMENT ON COLUMN TCL_CAM_ROLE.ROLE_ID IS 'Primary key for role';
COMMENT ON COLUMN TCL_CAM_ROLE.ROLE_NAME IS 'Name of the role (e.g. OPERATOR, MANAGER)';
COMMENT ON COLUMN TCL_CAM_ROLE.DESCRIPTION IS 'Description of role capabilities';
COMMENT ON COLUMN TCL_CAM_ROLE.CREATED_AT IS 'Timestamp when record was created';


-- USER
CREATE TABLE TCL_CAM_USER (
    USER_ID NUMBER NOT NULL,
    EMPLOYEE_ID VARCHAR2(50) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_TCL_CAM_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_TCL_CAM_USER_EMP_ID UNIQUE (EMPLOYEE_ID),
    CONSTRAINT FK_TCL_CAM_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TCL_CAM_ROLE(ROLE_ID)
);

COMMENT ON TABLE TCL_CAM_USER IS 'Application users and their credentials';
COMMENT ON COLUMN TCL_CAM_USER.USER_ID IS 'Primary key for user';
COMMENT ON COLUMN TCL_CAM_USER.EMPLOYEE_ID IS 'Unique employee identifier';
COMMENT ON COLUMN TCL_CAM_USER.FULL_NAME IS 'User full name';
COMMENT ON COLUMN TCL_CAM_USER.PASSWORD IS 'Password for the user';
COMMENT ON COLUMN TCL_CAM_USER.ROLE_ID IS 'Foreign key to TCL_CAM_ROLE';
COMMENT ON COLUMN TCL_CAM_USER.IS_ACTIVE IS 'Flag indicating if user is active (1=Yes, 0=No)';
COMMENT ON COLUMN TCL_CAM_USER.LAST_LOGIN IS 'Timestamp of last successful login';
COMMENT ON COLUMN TCL_CAM_USER.CREATED_AT IS 'Timestamp when record was created';
COMMENT ON COLUMN TCL_CAM_USER.UPDATED_AT IS 'Timestamp when record was last updated';


-- CHECKLIST
CREATE TABLE TCL_CAM_CHECKLIST (
    CHECKLIST_ID NUMBER NOT NULL,
    QUESTION VARCHAR2(500) NOT NULL,
    SEQUENCE_NO NUMBER NOT NULL,
    PHOTO_REQUIRED NUMBER(1) DEFAULT 0 NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY_USER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_TCL_CAM_CHECKLIST PRIMARY KEY (CHECKLIST_ID),
    CONSTRAINT UQ_TCL_CAM_CHK_SEQ UNIQUE (SEQUENCE_NO),
    CONSTRAINT CHK_TCL_CAM_CHK_SEQ CHECK (SEQUENCE_NO > 0),
    CONSTRAINT FK_TCL_CAM_CHK_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES TCL_CAM_USER(USER_ID)
);

COMMENT ON TABLE TCL_CAM_CHECKLIST IS 'Master list of inspection questions';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.CHECKLIST_ID IS 'Primary key for checklist question';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.QUESTION IS 'Text of the inspection question';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.SEQUENCE_NO IS 'Order of question execution';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.PHOTO_REQUIRED IS 'Flag if photo is mandatory (1=Yes, 0=No)';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.IS_ACTIVE IS 'Flag if question is active (1=Yes, 0=No)';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.CREATED_BY_USER_ID IS 'User who created the question';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.CREATED_AT IS 'Timestamp when record was created';
COMMENT ON COLUMN TCL_CAM_CHECKLIST.UPDATED_AT IS 'Timestamp when record was last updated';


-- INSPECTION
CREATE TABLE TCL_CAM_INSPECTION (
    INSPECTION_ID NUMBER NOT NULL,
    PART_NUMBER VARCHAR2(100) NOT NULL,
    SERIAL_NUMBER VARCHAR2(100) NOT NULL,
    VENDOR_CODE VARCHAR2(100),
    OPERATOR_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CURRENT_STEP NUMBER DEFAULT 0 NOT NULL,
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SUBMITTED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_TCL_CAM_INSPECTION PRIMARY KEY (INSPECTION_ID),
    CONSTRAINT CHK_TCL_CAM_INSP_STAT CHECK (STATUS IN ('IN_PROGRESS', 'SUBMITTED')),
    CONSTRAINT FK_TCL_CAM_INSP_OP FOREIGN KEY (OPERATOR_ID) REFERENCES TCL_CAM_USER(USER_ID)
);

COMMENT ON TABLE TCL_CAM_INSPECTION IS 'Header table for camshaft inspections';
COMMENT ON COLUMN TCL_CAM_INSPECTION.INSPECTION_ID IS 'Primary key for inspection';
COMMENT ON COLUMN TCL_CAM_INSPECTION.PART_NUMBER IS 'Part number being inspected';
COMMENT ON COLUMN TCL_CAM_INSPECTION.SERIAL_NUMBER IS 'Serial number being inspected';
COMMENT ON COLUMN TCL_CAM_INSPECTION.VENDOR_CODE IS 'Vendor code of the part';
COMMENT ON COLUMN TCL_CAM_INSPECTION.OPERATOR_ID IS 'Operator performing the inspection';
COMMENT ON COLUMN TCL_CAM_INSPECTION.STATUS IS 'Status of inspection (IN_PROGRESS, SUBMITTED)';
COMMENT ON COLUMN TCL_CAM_INSPECTION.CURRENT_STEP IS 'Last completed sequence number';
COMMENT ON COLUMN TCL_CAM_INSPECTION.STARTED_AT IS 'Timestamp when inspection started';
COMMENT ON COLUMN TCL_CAM_INSPECTION.SUBMITTED_AT IS 'Timestamp when inspection was completed';
COMMENT ON COLUMN TCL_CAM_INSPECTION.UPDATED_AT IS 'Timestamp when record was last updated';


-- PHOTO
CREATE TABLE TCL_CAM_PHOTO (
    PHOTO_ID NUMBER NOT NULL,
    INSPECTION_ID NUMBER NOT NULL,
    CHECKLIST_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    CONTENT_TYPE VARCHAR2(50) NOT NULL,
    FILE_SIZE NUMBER,
    IMAGE_DATA BLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TCL_CAM_PHOTO PRIMARY KEY (PHOTO_ID),
    CONSTRAINT FK_TCL_CAM_PHOTO_INSP FOREIGN KEY (INSPECTION_ID) REFERENCES TCL_CAM_INSPECTION(INSPECTION_ID),
    CONSTRAINT FK_TCL_CAM_PHOTO_CHK FOREIGN KEY (CHECKLIST_ID) REFERENCES TCL_CAM_CHECKLIST(CHECKLIST_ID)
);

COMMENT ON TABLE TCL_CAM_PHOTO IS 'Photos uploaded during inspection';
COMMENT ON COLUMN TCL_CAM_PHOTO.PHOTO_ID IS 'Primary key for photo';
COMMENT ON COLUMN TCL_CAM_PHOTO.INSPECTION_ID IS 'Inspection this photo belongs to';
COMMENT ON COLUMN TCL_CAM_PHOTO.CHECKLIST_ID IS 'Checklist question this photo relates to';
COMMENT ON COLUMN TCL_CAM_PHOTO.FILE_NAME IS 'Original file name';
COMMENT ON COLUMN TCL_CAM_PHOTO.CONTENT_TYPE IS 'MIME type of the photo';
COMMENT ON COLUMN TCL_CAM_PHOTO.FILE_SIZE IS 'Size of the photo in bytes';
COMMENT ON COLUMN TCL_CAM_PHOTO.IMAGE_DATA IS 'Binary image data';
COMMENT ON COLUMN TCL_CAM_PHOTO.CREATED_AT IS 'Timestamp when photo was uploaded';


-- RESPONSE
CREATE TABLE TCL_CAM_RESPONSE (
    RESPONSE_ID NUMBER NOT NULL,
    INSPECTION_ID NUMBER NOT NULL,
    CHECKLIST_ID NUMBER NOT NULL,
    RESULT VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PHOTO_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_TCL_CAM_RESPONSE PRIMARY KEY (RESPONSE_ID),
    CONSTRAINT CHK_TCL_CAM_RSP_RES CHECK (RESULT IN ('OK', 'NOT_OK')),
    CONSTRAINT FK_TCL_CAM_RSP_INSP FOREIGN KEY (INSPECTION_ID) REFERENCES TCL_CAM_INSPECTION(INSPECTION_ID),
    CONSTRAINT FK_TCL_CAM_RSP_CHK FOREIGN KEY (CHECKLIST_ID) REFERENCES TCL_CAM_CHECKLIST(CHECKLIST_ID),
    CONSTRAINT FK_TCL_CAM_RSP_PH FOREIGN KEY (PHOTO_ID) REFERENCES TCL_CAM_PHOTO(PHOTO_ID)
);

COMMENT ON TABLE TCL_CAM_RESPONSE IS 'Answers to checklist questions for an inspection';
COMMENT ON COLUMN TCL_CAM_RESPONSE.RESPONSE_ID IS 'Primary key for response';
COMMENT ON COLUMN TCL_CAM_RESPONSE.INSPECTION_ID IS 'Inspection this response belongs to';
COMMENT ON COLUMN TCL_CAM_RESPONSE.CHECKLIST_ID IS 'Checklist question being answered';
COMMENT ON COLUMN TCL_CAM_RESPONSE.RESULT IS 'Outcome (OK, NOT_OK)';
COMMENT ON COLUMN TCL_CAM_RESPONSE.DESCRIPTION IS 'Optional remarks or description';
COMMENT ON COLUMN TCL_CAM_RESPONSE.PHOTO_ID IS 'Optional foreign key to photo';
COMMENT ON COLUMN TCL_CAM_RESPONSE.CREATED_AT IS 'Timestamp when record was created';
COMMENT ON COLUMN TCL_CAM_RESPONSE.UPDATED_AT IS 'Timestamp when record was last updated';


-- AUDIT
CREATE TABLE TCL_CAM_AUDIT (
    AUDIT_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    ENTITY VARCHAR2(50) NOT NULL,
    ENTITY_ID NUMBER NOT NULL,
    ACTION VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TCL_CAM_AUDIT PRIMARY KEY (AUDIT_ID),
    CONSTRAINT FK_TCL_CAM_AUD_USER FOREIGN KEY (USER_ID) REFERENCES TCL_CAM_USER(USER_ID)
);

COMMENT ON TABLE TCL_CAM_AUDIT IS 'Audit log of critical operations';
COMMENT ON COLUMN TCL_CAM_AUDIT.AUDIT_ID IS 'Primary key for audit log';
COMMENT ON COLUMN TCL_CAM_AUDIT.USER_ID IS 'User performing the action';
COMMENT ON COLUMN TCL_CAM_AUDIT.ENTITY IS 'Table or object being modified';
COMMENT ON COLUMN TCL_CAM_AUDIT.ENTITY_ID IS 'Primary key of the modified record';
COMMENT ON COLUMN TCL_CAM_AUDIT.ACTION IS 'Action performed (INSERT, UPDATE, DELETE, etc.)';
COMMENT ON COLUMN TCL_CAM_AUDIT.DESCRIPTION IS 'Detailed description of the change';
COMMENT ON COLUMN TCL_CAM_AUDIT.CREATED_AT IS 'Timestamp of the action';


-- ----------------------------------------------------------------------------
-- 3. Indexes
-- ----------------------------------------------------------------------------
CREATE INDEX IDX_TCL_CAM_USER_ROLE ON TCL_CAM_USER(ROLE_ID);
CREATE INDEX IDX_TCL_CAM_CHK_USER ON TCL_CAM_CHECKLIST(CREATED_BY_USER_ID);
CREATE INDEX IDX_TCL_CAM_INSP_PART ON TCL_CAM_INSPECTION(PART_NUMBER);
CREATE INDEX IDX_TCL_CAM_INSP_SN ON TCL_CAM_INSPECTION(SERIAL_NUMBER);
CREATE INDEX IDX_TCL_CAM_INSP_OP ON TCL_CAM_INSPECTION(OPERATOR_ID);
CREATE INDEX IDX_TCL_CAM_INSP_STAT ON TCL_CAM_INSPECTION(STATUS);
CREATE INDEX IDX_TCL_CAM_RSP_INSP ON TCL_CAM_RESPONSE(INSPECTION_ID);
CREATE INDEX IDX_TCL_CAM_RSP_CHK ON TCL_CAM_RESPONSE(CHECKLIST_ID);
CREATE INDEX IDX_TCL_CAM_PHO_INSP ON TCL_CAM_PHOTO(INSPECTION_ID);
CREATE INDEX IDX_TCL_CAM_PHO_CHK ON TCL_CAM_PHOTO(CHECKLIST_ID);
CREATE INDEX IDX_TCL_CAM_AUD_USER ON TCL_CAM_AUDIT(USER_ID);

-- ----------------------------------------------------------------------------
-- 4. Triggers (Auto Increment)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_TCL_CAM_ROLE_PK
BEFORE INSERT ON TCL_CAM_ROLE
FOR EACH ROW
BEGIN
  IF :NEW.ROLE_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_ROLE.NEXTVAL INTO :NEW.ROLE_ID FROM SYS.DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TCL_CAM_USER_PK
BEFORE INSERT ON TCL_CAM_USER
FOR EACH ROW
BEGIN
  IF :NEW.USER_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_USER.NEXTVAL INTO :NEW.USER_ID FROM SYS.DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TCL_CAM_CHK_PK
BEFORE INSERT ON TCL_CAM_CHECKLIST
FOR EACH ROW
BEGIN
  IF :NEW.CHECKLIST_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_CHECKLIST.NEXTVAL INTO :NEW.CHECKLIST_ID FROM SYS.DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TCL_CAM_INSP_PK
BEFORE INSERT ON TCL_CAM_INSPECTION
FOR EACH ROW
BEGIN
  IF :NEW.INSPECTION_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_INSPECTION.NEXTVAL INTO :NEW.INSPECTION_ID FROM SYS.DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TCL_CAM_PHO_PK
BEFORE INSERT ON TCL_CAM_PHOTO
FOR EACH ROW
BEGIN
  IF :NEW.PHOTO_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_PHOTO.NEXTVAL INTO :NEW.PHOTO_ID FROM SYS.DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TCL_CAM_RSP_PK
BEFORE INSERT ON TCL_CAM_RESPONSE
FOR EACH ROW
BEGIN
  IF :NEW.RESPONSE_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_RESPONSE.NEXTVAL INTO :NEW.RESPONSE_ID FROM SYS.DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TCL_CAM_AUDIT_PK
BEFORE INSERT ON TCL_CAM_AUDIT
FOR EACH ROW
BEGIN
  IF :NEW.AUDIT_ID IS NULL THEN
    SELECT SEQ_TCL_CAM_AUDIT.NEXTVAL INTO :NEW.AUDIT_ID FROM SYS.DUAL;
  END IF;
END;
/
